### ISSUE TITLE
Logstash Forwarder repository is AWOL

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-logstash-forwarder#4]
See: https://github.com/elasticsearch/logstash-forwarder/issues/184.

We might have to build logstash-forwarder from source, which apparently involves installing Go and then building the binary with `go build`.

I'm going to leave this open for now in hopes that someone will step up and offer a package-based install, though... it would be much more convenient.

**Comment by jordansissel** [comment]
There was no such thing as an "official repository" for the logstash-forwarder.

**Comment by geerlingguy** [comment]
Updated the title; it was hosted on elasticsearch infrastructure, managed by elasticsearch... every indicator seemed to point to that being an officially-supported installation method (though not yet documented in the README).

**Comment by geerlingguy** [comment]
And, this entire project was replaced by Filebeat (https://github.com/elastic/beats/tree/master/filebeat)... so closing out this issue.
